services:

  backend:
    image: trendverse-backend
    depends_on:
      - redis
      - postgres
    build: 
      context: ./
      dockerfile: Dockerfile.backend
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis
    

  redis:
    image: trendverse-redis
    build: 
      context: ./ # Specify the build context directory for Redis
      dockerfile: Dockerfile.redis  # Specify the Dockerfile for Redis
    ports:
      - 6379:6379

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=furkan6802
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data_new
    volumes:
      - ./trendverse_schema.sql:/docker-entrypoint-initdb.d/trendverse_schema.sql
    
    